### ISSUE TITLE
Can't install / use on Windows

### ISSUE THREAD

**Issue by iamthekings5** [peerdavid/remapy#17] opened 2020-11-16 14:07 UTC
Hey,

I've been trying to get this running but I can't seem to figure it out. I have tried this with Python 3.9.0 and when that failed I installed Python 3.6.0 but still to no avail.

The install.bat opens and closes instantly and it seems like it was executed without any issues. There was nothing logged after the two lines were executed. I tried running the install.sh file and some things were happening but the launch.bat/sh files still did nothing.

Do let me know what I can do to help troubleshoot the issue as I hope to get this running to replace the reMarkable desktop app (it sucks).

**Comment by peerdavid** [comment] 2020-11-27 11:47
I'm really sry, but I have no Windows PC and I'm currently not interested to setup one i.e. I can not test/reproduce our problem. But probably @ivovh can help who implemented the scripts?

Cheers, David

**Comment by ivovh** [comment] 2020-11-27 20:47
Hi @iamthekings5,

The scripts should work if the `python3` executable is present in one of the directories in your default %PATH%. Maybe you can try to run them manually from a command line prompt, instead of double clicking on them, to check if that works for you?

**Comment by Pemo11235** [comment] 2020-12-25 18:56
In Windows 2004 is there a issue related to numpy.

To solve, downgrade yourr numpy .
pip install numpy==1.19.3

**Comment by silenzi71** [comment] 2021-01-11 18:31
I think that the workaround of downgrading numpy would not be enough. On my side, I solved commenting the Numpy sanity check, and now the application runs; the file explorer seems to work fine.
However, the backup function does not work properly. It stops after few files (which are in the trash). I guess that file naming convention prevents it to complete the task at a certain point.

**Comment by peerdavid** [comment] 2021-01-11 20:06
Hello,

I tried to reproduce your backup problem on Linux - I also have some files in the trash but the backup still works. 

> I guess that file naming convention prevents it to complete the task at a certain point.
Can you elaborate a little bit more about how you named the files? Or is it possible that windows does not allow all filenames (containing '/' etc.) ?

Thank you, 
David

**Comment by silenzi71** [comment] 2021-01-24 14:37
> Hello,
> 
> I tried to reproduce your backup problem on Linux - I also have some files in the trash but the backup still works.
> 
> > I guess that file naming convention prevents it to complete the task at a certain point.
> > Can you elaborate a little bit more about how you named the files? Or is it possible that windows does not allow all filenames (containing '/' etc.) ?
> 
> Thank you,
> David

Hi David,
after a while, I was able to gain what apparently is a full backup of my documents on the tablet.
It was necessary to solve naming issues about them, in particular those who came from a "read on remarkable" web pages printing, since the title of the webpage becomes the name of the document, regardless of its compliance to standard naming conventions.

Your batch launcher window was helpful in spotting a couple of them. However, there were others which did not generate any error (with a successful backup message box from the application), but resulted in a "zero-length" file. To give you an idea: documents with a colon or inverted commas are signalled in the batch window, but other with backslashes are not.
It would be a good idea, in your routine, to replace these characters automatically, for example with their ASCII code number, and signal in the batch window if the backup routine generates a zero-length file (a simple check after file creation might do).

If there are more documents with the same title (as it may happen with sharing files from apps or websites to the tablet), the result is an overwriting in the backup, with no message or control on that behaviour. So, instead of having multiple documents with the same "title", like happens on the tablet, you end with a single file (which will be only one of them, you will never know which). In this case, a numbering routine might solve the problem and create, correctly, the expected number of files.

Finally, I would like to report an issue with pdf rendering. When you export a pdf file which has annotations that go beyond the page limit (is it possible to do this by the "adjust view" function of the tablet: it allows you to go over the page limits), they appear trimmed when you open them. Playing with Acrobat pro, or Scribus, you realize that export was correct, and the whole annotations are still there (you can move them within the page limits). When you export by sending e-mail from remarkable tablet, or using the companion app, this problem doesn't occur, and the pdf page size is adjusted accordingly.

Let me conclude telling you how much I like your application, which provides features that are missing in the companion app, and makes content browsing very handy, despite the absence of a thumbnail preview. The option of exporting only the modified page of a pdf is so clever!
A very useful information you could add in the file explorer is the number of files shown, and within each directory.

Thanks a lot for your patience in reading this, and for your outstanding coding.

Andrea Silenzi

**Comment by peerdavid** [comment] 2021-01-24 15:43
Hello,

thank you very much for your detailed analysis! 

> Your batch launcher window was helpful in spotting a couple of them. However, there were others which did not generate any error (with a successful backup message box from the application), but resulted in a "zero-length" file. To give you an idea: documents with a colon or inverted commas are signalled in the batch window, but other with backslashes are not. It would be a good idea, in your routine, to replace these characters automatically, for example with their ASCII code number, and signal in the batch window if the backup routine generates a zero-length file (a simple check after file creation might do).

I have to think about how I can implement this because I think there are differences between Mac / Linux / Windows. My main goal is still to develop a Linux reMarkable GUI, but if I can additionally support Windows I will try to do this.


> If there are more documents with the same title (as it may happen with sharing files from apps or websites to the tablet), the result is an overwriting in the backup, with no message or control on that behaviour. So, instead of having multiple documents with the same "title", like happens on the tablet, you end with a single file (which will be only one of them, you will never know which). In this case, a numbering routine might solve the problem and create, correctly, the expected number of files.

Thank you very much for pointing this out - I never considered this case... I created a new issue.

> Finally, I would like to report an issue with pdf rendering. When you export a pdf file which has annotations that go beyond the page limit (is it possible to do this by the "adjust view" function of the tablet: it allows you to go over the page limits), they appear trimmed when you open them. Playing with Acrobat pro, or Scribus, you realize that export was correct, and the whole annotations are still there (you can move them within the page limits). When you export by sending e-mail from remarkable tablet, or using the companion app, this problem doesn't occur, and the pdf page size is adjusted accordingly.

I have done this by design: When I implemented it I had the choice to keep the original pdf size or to resize each page (or single pages) of the pdf. I decided to keep the original pdf because I thought rendering is faster and (now I will tell you the real reason ^^) it was also much easier for me to implement and it saved me lots of time :-P

Thank you again,
David

**Comment by drewsed** [comment] 2021-05-31 18:03
Installed this on a fresh win10 machine today and everything worked fine after setting the right environment variables (path).

**Comment by peerdavid** [comment] 2021-05-31 18:12
@drewsed  Thanks a lot for this info! I will close this issue now.

**Closed by peerdavid** 2021-05-31 18:12 UTC
Labels: question
